-- TODO:
-- local lsp = require('lsp-zero')
-- lsp.preset('recommended')
-- 
-- 
-- --lsp.ensure_installed({
-- --    'lua_ls',
-- --    'rust_analyzer',
-- --})
-- 
-- --local cmp = require('cmp')
-- --local cmp_select = {behaviour = cmp.SelectBehaviour.Select}
-- --local cmp_mappings = lsp.defaults.cmp_mappings({
-- --	['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
-- --	['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
-- --	['<C-y>'] = cmp.mapping.confirm({ select = true }),
-- --	["<C-Space>"] = cmp.mapping.complete(),
-- --})
-- 
-- require('mason').setup({})
-- 
-- require('mason-lspconfig').setup({
--   ensure_installed = {},
--   handlers = {
--     lsp.default_setup,
--   },
-- })
-- 
-- lsp.on_attach(function(client, bufnr)
-- --    local opts = { buffer = bufnr, remap = false }
-- 
--     vim.keymap.set('n', '<leader>f', function() vim.lsp.buf.format { async = true } end, opts)
-- 
--    -- require('lsp-inlayhints').on_attach(client, bufnr)
-- 
--     --    local opts = {buffer = bufnr, remap = false}
--     --
--     --    vim.keymap.set("n", "gd",          function() vim.lsp.buf.definitions()      end, opts)
--     --    vim.keymap.set("n", "K",           function() vim.diagnostic.hover()         end, opts)
--     --    vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
-- --    vim.keymap.set("n", "<leader>vd",  function() vim.diagnostic.open_float()    end, opts)
--     --    vim.keymap.set("n", "[d",          function() vim.diagnostic.goto_next()     end, opts)
--     --    vim.keymap.set("n", "]d",          function() vim.diagnostic.goto_prev()     end, opts)
--     --    vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action()      end, opts)
-- --    vim.keymap.set("n", "<leader>gr", function() vim.lsp.buf.references()       end, opts)
--     vim.keymap.set("n", "<Leader>a",   function () vim.lsp.buf.code_action() end, opts)
-- --    vim.keymap.set("n", "<leader>vrr", function()  vim.lsp.buf.references()  end, opts)
-- --    vim.keymap.set("n", "<leader>vrn", function()  vim.lsp.buf.rename()      end, opts)
--     --    vim.keymap.set("i", "<C-h>",       function() vim.lsp.buf.signature_help()   end, opts)
-- 
--     --Default settings:
--     --(no idea if im gonna need this)
--     lsp.default_keymaps({ buffer = bufnr })
-- end)
-- 
-- lsp.setup()
